### ISSUE TITLE
Option to disable disk metrics from collectd/signalfx-metadata

### ISSUE THREAD

**Issue by jalaziz** [signalfx/signalfx-agent#1177] opened 2020-01-29 08:58 UTC
Given that several golang monitors now officially replace their collectd counterparts, it would be great if we could do the same for the `filesystems` monitor.

Currently, `filesystems` duplicates some metrics sent by `collectd/signalfx-metadata` and, unfortunately, `collectd/signalfx-metadata` does not support omitting disk info like it does for process info.

While it is possible to use `datapointsToExclude` to omit sending the metrics from the collectd monitor, it would be great if there was a more obvious and simple way to ensure both monitors can be run simultaneously.

**Comment by keitwb** [comment] 2020-01-29 13:27
@jalaziz do you mean the `disk.utilization` metric that `collectd/signalfx-metadata` emits?  If you turn off the `collectd/df` plugin and replace it with the `filesystems` plugin, the `collectd/signalfx-metadata` monitor should no longer emit `disk.utilization`, but it would be emitted by the `filesystems` monitor only.  One potentially confusing thing is that the `disk.utilization` metric in 4.x of the agent has a dimension `plugin: signalfx-metadata`, but that will be removed in the 5.0 release (pending release in the next few weeks) so that piece of cruft will go away then.  See if that is what you are seeing, but if not, let me know.

**Comment by jalaziz** [comment] 2020-02-07 23:43
@keitwb Sorry! Didn't get notified for some reason.

Indeed, I meant `disk.utilization` and `disk.summary_utilization`.

Thanks for the tip, didn't realize disabling `collectd/df` would also disable those metrics!

We don't use the `plugin` dimension, so that should be fine unless it is used to trigger something on the SignalFx UI?

I will test it out soon and post the results.

**Comment by keitwb** [comment] 2020-02-09 22:37
Ok cool.  Anything in the UI that is used as a trigger will be updated before release.  Let me know if you run into any issues.

**Comment by jalaziz** [comment] 2020-02-10 10:59
@keitwb Replacing `collectd/df` with `filesystems` worked fine, however there were a couple "breaking" differences.

1. With `collectd/df`, mount paths are normalized. For example, a `/var/lib` mount would have `plugin_instance:var-lib`. With `filesystems`, we have `plugin_instance:/var/lib`. Arguably, `filesystems` is more correct, but it does break existing detectors.

2. With `collectd/df`, the root mount path has `plugin_instance:root`. With `filesystems`, we have `plugin_instance:` and `mountpoint:` (empty strings). Shouldn't they be `/`?

**Comment by keitwb** [comment] 2020-02-10 14:07
For 1. Yes, the filesystem monitor the change from `-` to the conventional `/` separator is going to be a breaking change.  Also in the 5.0 release, `filesystems` will no longer emit a `plugin_instance` dimension at all, it will just have `mountpoint`, `device`, and `fs_type` dimensions.

For 2. this is a bug due to overly simplistic stripping of the hostfs mountpoint prefix that I have confirmed (I'm assuming you are running the agent in some kind of containerized environment and not straight on the host).  It should be fixed in #1190 which will go out in 5.0 (might backport it to 4.x but not high priority since we are about to release 5.0).

I also added a guide for migrating in #1190.  The easiest thing to do to transition detectors seamlessly without any false alerts or downtime is to run both monitors simultaneously, switch your detectors, then turn off the `collectd/df` monitor in your configs.  You will still be able to run `collectd/df` (and `collectd/signalfx-metadata`) in 5.0 so you won't be forced to change them right away.  You should not (need to confirm this) be charged for any extra usage when both monitors are active due to how the accounting works since the metric names are the same and the hostname would be the same.

**Comment by keitwb** [comment] 2020-02-11 13:46
Going to close this unless you have any other issues/concerns about this.

**Closed by keitwb** 2020-02-11 13:46 UTC
