### ISSUE TITLE
metrics monitor `container_cpu_utilization` is seconds not percentages

### ISSUE THREAD

**Issue by NZTimKeegan** [signalfx/signalfx-agent#2491] opened 2022-09-26 22:27 UTC
The docs for the `kubelet-metrics` monitor states the `container_cpu_utilization` metrics is "Cumulative cpu utilization in percentages" (as per: https://github.com/signalfx/signalfx-agent/blob/a41fb5c94d53fb46db06a0cf3490b3aae8ce7da9/pkg/monitors/cadvisor/converter/converter.go#L133)

I believe the datapoint it is referring to is: https://github.com/google/cadvisor/blob/967136f459d7515668ce587881e4dd61775e9499/info/v1/container.go#L286. This is a measure of total cpu time in nanoseconds.

The same source is used for another metric (`container_cpu_usage_seconds_total`), which is labelled as nanoseconds https://github.com/signalfx/signalfx-agent/blob/a41fb5c94d53fb46db06a0cf3490b3aae8ce7da9/pkg/monitors/cadvisor/converter/converter.go#L125 

Dividing nanoseconds by 10000000 will tell us how many ~~seconds~~ centi-seconds of cpu time has been used, but I don't believe this is a percentage.

The label should be "Cumulative cpu utilization in ~~seconds~~ centi-seconds".

**Comment by rmfitzpatrick** [comment] 2023-02-01 21:24
@NZTimKeegan thanks for your report (and patience). I believe this is [by design](https://github.com/signalfx/signalfx-agent/blob/main/docs/monitors/kubelet-stats.md#metrics) and centiseconds, "centicores", and percent aren't mutually exclusive, though I do think something like "core-centiseconds" would be more accurate:

>Cumulative cpu utilization in percentages. This is equivalent to "centicores", or hundreths [sic] of CPU cores consumed. This metric is NOT normalized by the total # of cores on the system.

100% utilization for a core over one second is 100 centicores (10^9/10^7). This way when using a rate/s rollup for this metric over any interval it is reflective of the non-normalized per-100 (i.e. "percent") utilization, but with the consequence of a delta being necessary for relative values.

Comparing to the corresponding kubeletstats receiver in the collector (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md#containercpuutilization), this metric is now a gauge since the updated api type provides the average/relative value for us: https://github.com/kubernetes/kubelet/blob/master/pkg/apis/stats/v1alpha1/types.go#L207. That value is divided by 10^9 to be in [0,<num_cores>], though for backwards compatibility we have the option of reporting `container_cpu_utilization` based on the `container.cpu.time` sum.

**Comment by atoulme** [comment] 2023-02-14 17:20
Closing this issue - please note the Smart Agent is deprecated, and we recommend you look at the OpenTelemetry Collector going forward. Thanks!

**Closed by atoulme** 2023-02-14 17:20 UTC
